-- ================================================================
-- SCRIPT DE CORRECCIONES DE CONVOCATORIA
-- Generado: 2026-01-11 14:57:03
-- ================================================================
-- 
-- RESUMEN:
-- - Vacantes FII a crear: 11 (El Tarra: 5, San Vicente: 3, Santa Rosa: 3)
-- - Vacantes duplicadas a eliminar: 36 (FII: 30, FCAS: 6)
-- - Vacantes FII extras a eliminar: 10
-- 
-- NOTA: Todas las vacantes a eliminar han sido verificadas sin postulaciones
-- ================================================================

START TRANSACTION;

-- ================================================================
-- 1. CREAR VACANTES FII FALTANTES
-- ================================================================

-- El Tarra
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1057, 'FII-04', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - MICROBIOLOGO', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-04 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>MICROBIOLOGIA - INOCUIDAD EN LOS PROCESOS AGROINDUSTRIALES</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>El Tarra</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'El Tarra', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">MICROBIOLOGO</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede El Tarra en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1058, 'FII-05', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - LICENCIADO EN IDIOMAS O LENGUAS EXTRANJERAS O LENGUAS MODERNAS O AREAS AFINES', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-05 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>INGLES I – INGLES II – INGLES III</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>El Tarra</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'El Tarra', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">LICENCIADO EN IDIOMAS O LENGUAS EXTRANJERAS O LENGUAS MODERNAS O AREAS AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede El Tarra en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1059, 'FII-06', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - INGENIERO DE ALIMENTOS/ INGENIERO AGROINDUSTRIAL/ INGENIERO DE PRODUCCION AGROIN', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-06 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>INTRODUCCION A LA AGROINDUSTRIA - PROCESOS AGROALIMENTARIOS – MATERIAS PRIMAS Y POSCOSECHA - PROCESAMIENTO DE PRODUCTOS</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>El Tarra</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'El Tarra', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">INGENIERO DE ALIMENTOS/ INGENIERO AGROINDUSTRIAL/ INGENIERO DE PRODUCCION AGROINDUSTRIAL O AREAS AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede El Tarra en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1060, 'FII-07', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - INGENIERO DE ALIMENTOS/ INGENIERO AGROINDUSTRIAL/ INGENIERO DE PRODUCCION AGROIN', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-07 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>OPTATIVA I DE PROFUNDIZACIÓN, AGROINDUSTRIA NO ALIMENTARIA I, AGROINDUSTRIA NO ALIMENTARIA II</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>El Tarra</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'El Tarra', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">INGENIERO DE ALIMENTOS/ INGENIERO AGROINDUSTRIAL/ INGENIERO DE PRODUCCION AGROINDUSTRIAL O AREAS AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede El Tarra en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1061, 'FII-08', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - INGENIERO DE ALIMENTOS- INGENIERO QUÍMICO O PROFESIONES AFINES', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-08 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>FISICOQUÍMICA AGROINDUSTRIAL Y PROCESOS DE TRANSFORMACIÓN FISICOQUÍMICA</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>El Tarra</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'El Tarra', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">INGENIERO DE ALIMENTOS- INGENIERO QUÍMICO O PROFESIONES AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede El Tarra en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);

-- San Vicente del Chucurí
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1062, 'FII-04', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - MICROBIOLOGO', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-04 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>MICROBIOLOGIA</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>San Vicente del Chucurí</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'San Vicente del Chucurí', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">MICROBIOLOGO</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede San Vicente del Chucurí en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1063, 'FII-05', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - LICENCIADO EN IDIOMAS O LENGUAS EXTRANJERAS O LENGUAS MODERNAS O AREAS AFINES', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-05 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>INGLES I – INGLES II</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>San Vicente del Chucurí</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'San Vicente del Chucurí', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">LICENCIADO EN IDIOMAS O LENGUAS EXTRANJERAS O LENGUAS MODERNAS O AREAS AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede San Vicente del Chucurí en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1064, 'FII-06', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - INGENIERO DE ALIMENTOS O INGENIERO AGROINDUSTRIAL O DE PRODUCCION AGROINDUSTRIAL', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-06 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>INTRODUCCION A LA AGROINDUSTRIA - PROCESOS AGROALIMENTARIOS- PROCESOS NO AGROALIMENTARIOS- MATERIAS PRIMAS Y POSTCOSECHA</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>San Vicente del Chucurí</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'San Vicente del Chucurí', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">INGENIERO DE ALIMENTOS O INGENIERO AGROINDUSTRIAL O DE PRODUCCION AGROINDUSTRIAL O AREAS AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede San Vicente del Chucurí en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);

-- Santa Rosa del Sur
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1065, 'FII-04', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - MICROBIOLOGO', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-04 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>MICROBIOLOGIA</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>Santa Rosa del Sur</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'Santa Rosa del Sur', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">MICROBIOLOGO</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede Santa Rosa del Sur en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1066, 'FII-05', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - LICENCIADO EN IDIOMAS O LENGUAS EXTRANJERAS O LENGUAS MODERNAS O AREAS AFINES', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-05 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>INGLES I – INGLES II</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>Santa Rosa del Sur</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'Santa Rosa del Sur', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">LICENCIADO EN IDIOMAS O LENGUAS EXTRANJERAS O LENGUAS MODERNAS O AREAS AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede Santa Rosa del Sur en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);
INSERT INTO mdl_local_jobboard_vacancy (id, code, title, description, contracttype, duration, location, modality, department, companyid, departmentid, convocatoriaid, programid, positions, requirements, desirable, status, publicationtype, opendate, closedate, createdby, modifiedby, timecreated, timemodified) VALUES (1067, 'FII-06', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES - INGENIERO DE ALIMENTOS O INGENIERO AGROINDUSTRIAL O DE PRODUCCION AGROINDUSTRIAL', '<div class="vacancy-description"><div class="alert alert-secondary"><strong>Código:</strong> FII-06 | <strong>Facultad:</strong> Ingenierías e Innovación | <strong>Modalidad:</strong> Distancia</div><h4>Programa Académico</h4><p><strong>TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES</strong></p><h4>Actividades/Cursos a Orientar</h4><p>INTRODUCCION A LA AGROINDUSTRIA - PROCESOS AGROALIMENTARIOS- PROCESOS NO AGROALIMENTARIOS- MATERIAS PRIMAS Y POSTCOSECHA</p><h4>Información de la Vinculación</h4><table class="table table-sm"><tr><th>Tipo de Vinculación</th><td><span class="badge badge-primary">Hora Cátedra</span></td></tr><tr><th>Duración</th><td>Semestre académico (16 semanas)</td></tr><tr><th>Sede</th><td>Santa Rosa del Sur</td></tr><tr><th>Modalidad</th><td>Distancia</td></tr><tr><th>Facultad</th><td>Ingenierías e Innovación</td></tr></table></div>', 'catedra', 'Semestre académico (16 semanas)', 'Santa Rosa del Sur', 'distancia', 'TECNOLOGÍA EN PROCESOS AGROINDUSTRIALES', NULL, NULL, 1, NULL, 1, '<div class="vacancy-requirements"><h5>Perfil Profesional Requerido</h5><p class="lead">INGENIERO DE ALIMENTOS O INGENIERO AGROINDUSTRIAL O DE PRODUCCION AGROINDUSTRIAL O AREAS AFINES</p><h5>Requisitos Mínimos</h5><ul><li>Título profesional universitario acorde al perfil solicitado</li><li>No tener inhabilidades ni incompatibilidades para contratar con el Estado</li><li>Disponibilidad para la sede Santa Rosa del Sur en modalidad Distancia</li></ul></div>', '<div class="vacancy-desirable"><h5>Requisitos Deseables</h5><ul><li>Experiencia docente en educación superior mínimo 1 año</li><li>Manejo de herramientas tecnológicas para educación virtual</li></ul></div>', 'published', 'public', NULL, NULL, 2, NULL, 1768143423, 1768143423);

-- ================================================================
-- 2. ELIMINAR VACANTES DUPLICADAS (sufijo a/b)
-- Total: 36 vacantes
-- ================================================================

DELETE FROM mdl_local_jobboard_vacancy WHERE id IN (757, 758, 759, 760, 793, 794, 919, 920, 921, 922, 925, 926, 961, 962, 963, 964, 967, 968, 1011, 1012, 1013, 1014, 1017, 1018, 1049, 1050, 1051, 1052, 1055, 1056, 749, 750, 815, 816, 818, 819);

-- ================================================================
-- 3. ELIMINAR VACANTES FII EXTRAS EN CT
-- Total: 10 vacantes
-- ================================================================

DELETE FROM mdl_local_jobboard_vacancy WHERE id IN (915, 923, 924, 957, 966, 1007, 1016, 1045, 1053, 1054);

COMMIT;

-- ================================================================
-- FIN DEL SCRIPT
-- ================================================================